function reportserver(){var O='bootstrap',P='begin',Q='gwt.codesvr.reportserver=',R='gwt.codesvr=',S='reportserver',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='reportserver::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='reportserver.nocache.js',Ib='base',Jb='//',Kb='gxt.user.agent',Lb='chrome',Mb='opera',Nb='trident',Ob='msie',Pb=11,Qb='ie11',Rb=10,Sb='ie10',Tb=9,Ub='ie9',Vb=8,Wb='ie8',Xb='msie 7',Yb='ie7',Zb='msie 6',$b='ie6',_b='safari',ac='version/3',bc='safari3',cc='version/4',dc='safari4',ec='safari5',fc='gecko',gc='rv:1.8',hc='gecko1_8',ic='gecko1_9',jc='adobeair',kc='air',lc=2,mc=3,nc=4,oc=5,pc=6,qc=7,rc='user.agent',sc='webkit',tc='user.agent.os',uc='macintosh',vc='mac os x',wc='mac',xc='linux',yc='windows',zc='win32',Ac='unknown',Bc='selectingPermutation',Cc='reportserver.devmode.js',Dc='22A5B95DBD10B3E842F6EA87AA1AEC75',Ec=':1',Fc=':2',Gc=':3',Hc='39304B43A13FE5CFB54A27BA70407F89',Ic='46CDDDFC73C3DDFC2C646CC616A9A6D7',Jc=':10',Kc=':11',Lc=':4',Mc=':5',Nc=':6',Oc=':7',Pc=':8',Qc=':9',Rc='4C8593C4491F5DFBC985151EA36783F6',Sc='61514853A03FE56933FDD0CE3C975125',Tc='816413FD542619750DA20234B44F5F58',Uc='98320FF91A0D345F662095C4D7F8F853',Vc='A932A5288AC623BA344830DC2E50DA40',Wc='ADC8E5840C6335E94FA48192984B1B9C',Xc='C340917A006859230B6B3CA029CBC0C8',Yc='D1CE02F2F18D3E41C559D00AC6591F13',Zc='D587426696D79FD27D8CD29DAB59E15A',$c=':',_c='.cache.js',ad='link',bd='rel',cd='stylesheet',dd='href',ed='loadExternalRefs',fd='reset.css',gd='end',hd='http:',jd='file:',kd='_gwt_dummy_',ld='__gwtDevModeHook:reportserver',md='Ignoring non-whitelisted Dev Mode URL: ',nd=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
reportserver.__sendStats=r;reportserver.__moduleName=S;reportserver.__errFn=null;reportserver.__moduleBase=U;reportserver.__softPermutationId=V;reportserver.__computePropValue=null;reportserver.__getPropMap=null;reportserver.__installRunAsyncCode=function(){};reportserver.__gwtStartLoadingFragment=function(){return null};reportserver.__gwt_isKnownPropertyValue=function(){return false};reportserver.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};reportserver.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[reportserver.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
reportserver.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(reportserver.__errFn){n.onerror=function(){reportserver.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
reportserver.__startLoadingFragment=function(a){return D(a)};reportserver.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;reportserver.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return reportserver.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Lb)!=-1)return Lb;if(a.indexOf(Mb)!=-1)return Mb;if(a.indexOf(Nb)!=-1||a.indexOf(Ob)!=-1){if(p.documentMode>=Pb)return Qb;if(p.documentMode>=Rb)return Sb;if(p.documentMode>=Tb)return Ub;if(p.documentMode>=Vb)return Wb;if(a.indexOf(Xb)!=-1)return Yb;if(a.indexOf(Zb)!=-1)return $b;return Sb}if(a.indexOf(_b)!=-1){if(a.indexOf(ac)!=-1)return bc;if(a.indexOf(cc)!=-1)return dc;return ec}if(a.indexOf(fc)!=-1){if(a.indexOf(gc)!=-1)return hc;return ic}if(a.indexOf(jc)!=-1)return kc;return null};i[Kb]={air:V,chrome:W,gecko1_8:lc,gecko1_9:mc,ie10:nc,ie11:oc,ie8:pc,ie9:qc,safari3:Vb,safari4:Tb,safari5:Rb};j[rc]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(sc)!=-1}())return _b;if(function(){return a.indexOf(Ob)!=-1&&(b>=Rb&&b<Pb)}())return Sb;if(function(){return a.indexOf(Ob)!=-1&&(b>=Tb&&b<Pb)}())return Ub;if(function(){return a.indexOf(Ob)!=-1&&(b>=Vb&&b<Pb)}())return Wb;if(function(){return a.indexOf(fc)!=-1||b>=Pb}())return hc;return bb};i[rc]={gecko1_8:V,ie10:W,ie8:lc,ie9:mc,safari:nc};j[tc]=function(){var a=o.navigator.userAgent.toLowerCase();if(a.indexOf(uc)!=-1||a.indexOf(vc)!=-1){return wc}if(a.indexOf(xc)!=-1){return xc}if(a.indexOf(yc)!=-1||a.indexOf(zc)!=-1){return yc}return Ac};i[tc]={linux:V,mac:W,unknown:lc,windows:mc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};reportserver.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};reportserver.__computePropValue=k;o.__gwt_activeModules[S].bindings=reportserver.__getPropMap;r(O,Bc);if(q()){return D(Cc)}var l;try{h([Sb,Sb,xc],Dc);h([Sb,Sb,wc],Dc+Ec);h([Sb,Sb,Ac],Dc+Fc);h([Sb,Sb,yc],Dc+Gc);h([Qb,Wb,xc],Hc);h([Qb,Wb,wc],Hc+Ec);h([Qb,Wb,Ac],Hc+Fc);h([Qb,Wb,yc],Hc+Gc);h([kc,_b,xc],Ic);h([kc,_b,wc],Ic+Ec);h([ec,_b,Ac],Ic+Jc);h([ec,_b,yc],Ic+Kc);h([kc,_b,Ac],Ic+Fc);h([kc,_b,yc],Ic+Gc);h([Lb,_b,xc],Ic+Lc);h([Lb,_b,wc],Ic+Mc);h([Lb,_b,Ac],Ic+Nc);h([Lb,_b,yc],Ic+Oc);h([ec,_b,xc],Ic+Pc);h([ec,_b,wc],Ic+Qc);h([Wb,Wb,xc],Rc);h([Wb,Wb,wc],Rc+Ec);h([Wb,Wb,Ac],Rc+Fc);h([Wb,Wb,yc],Rc+Gc);h([bc,_b,xc],Sc);h([bc,_b,wc],Sc+Ec);h([bc,_b,Ac],Sc+Fc);h([bc,_b,yc],Sc+Gc);h([dc,_b,xc],Sc+Lc);h([dc,_b,wc],Sc+Mc);h([dc,_b,Ac],Sc+Nc);h([dc,_b,yc],Sc+Oc);h([Qb,hc,xc],Tc);h([Qb,hc,wc],Tc+Ec);h([Qb,hc,Ac],Tc+Fc);h([Qb,hc,yc],Tc+Gc);h([Qb,_b,xc],Uc);h([Qb,_b,wc],Uc+Ec);h([Qb,_b,Ac],Uc+Fc);h([Qb,_b,yc],Uc+Gc);h([hc,hc,xc],Vc);h([hc,hc,wc],Vc+Ec);h([hc,hc,Ac],Vc+Fc);h([hc,hc,yc],Vc+Gc);h([Qb,Sb,xc],Wc);h([Qb,Sb,wc],Wc+Ec);h([Qb,Sb,Ac],Wc+Fc);h([Qb,Sb,yc],Wc+Gc);h([ic,hc,xc],Xc);h([ic,hc,wc],Xc+Ec);h([ic,hc,Ac],Xc+Fc);h([ic,hc,yc],Xc+Gc);h([Qb,Ub,xc],Yc);h([Qb,Ub,wc],Yc+Ec);h([Qb,Ub,Ac],Yc+Fc);h([Qb,Ub,yc],Yc+Gc);h([Ub,Ub,xc],Zc);h([Ub,Ub,wc],Zc+Ec);h([Ub,Ub,Ac],Zc+Fc);h([Ub,Ub,yc],Zc+Gc);l=f[k(Kb)][k(rc)][k(tc)];var m=l.indexOf($c);if(m!=-1){g=parseInt(l.substring(m+W),Rb);l=l.substring(V,m)}}catch(a){}reportserver.__softPermutationId=g;return D(l+_c)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(ad);b.setAttribute(bd,cd);b.setAttribute(dd,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(ed,P);c(fd);c(fd);r(ed,gd)}
B();reportserver.__moduleBase=C();t[S].moduleBase=reportserver.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==hd||o.location.protocol==jd);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=kd;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=ld;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(md+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+nd]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,gd);A(H);return true}
reportserver.succeeded=reportserver();